name: Approval Workflow

on:
    pull_request_review:
      types: [submitted]
jobs:
    approved:
        # if: github.event.review.state == 'approved'
        uses: dani-chmb/amazon-ecs-deploy-task-definition/.github/workflows/dummy-workflow.yml@integ-tests
        with:
          branch-name: ${{ github.head_ref }}
              