# TODO:
# When this is called from another branch, make sure you can echo the parameter provided by the other branch. This should be branch name. 
name: dummy

on:
    workflow_call:
        inputs:
            branch-name:
                description: 'The branch to do nothing on'
                required: true
                type: string
        outputs:
            success-message:
                value: ${{ jobs.do-nothing.outputs.output1 }}
    push:
        branches:
        - integ-tests

jobs:
    do-nothing:
        name: Do Nothing
        runs-on: ubuntu-latest
        outputs:
            output1: ${{ steps.workflow-call-test.outputs.success-message}}

        steps:
            - id: workflow-call-test
              if: github.event_name == 'workflow_call'
              run: |
                echo "Im being invoked by the following branch: ${{ inputs.branch-name }}" >> $GITHUB_OUTPUT
            - name: Push call tests
              if: github.event_name == 'push'
              run: |
                echo "I'm being invoked by push"


