on:
  push:
    branches:
      - integ-tests
  workflow_call: # Turns this workflow into a reusable workflow that can be called from another branch upon PR approval
    inputs:
      # !! This parameter is used because we can't use `if: ${{ github.event_name != 'workflow_call' }}`
      # https://github.com/actions/runner/issues/3146
      call_local_action:
          type: string
          required: true
    # !! Reused workflows cannot access secrets directly, they must be passed by the caller workflow
    # https://docs.github.com/en/actions/sharing-automations/reusing-workflows#using-inputs-and-secrets-in-a-reusable-workflow
    secrets:
      account_id:
          required: true

name: Integration Test

permissions:
  id-token: write
  contents: read

jobs:
  # !! Rename `deploy` job to `deploy_from_push` to differentiate from the `deploy_from_local_action`. 
  # This job would be run as part of the regular CICD Infrastructure
  # https://w.amazon.com/bin/EC2/Project_Madison/BDX/Projects/ECSGithubActions#HECSGitHubActionCICDInfrastructurePhases
  deploy_from_push:
    if: github.event_name == 'push'
    name: Deploy from push
    runs-on: ubuntu-latest

    # !! For simplicity's sake, most steps have been commented out for this job.
    # The exception being the 'Print current build ID' step, which is used as a sanity check
    steps:
    # - name: Checkout
    #   uses: actions/checkout@v2

    - name: Print current build ID
      run: |
        echo Integration test run: githubactionsamazonecsdeplo-NWcjHIgDJLXw:326df341-4a50-42b7-a7fc-4990eb33ded7

    # - name: Configure AWS credentials
    #   uses: aws-actions/configure-aws-credentials@v4
    #   with:
    #     role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GitHubActionsDeployTaskIntegrationTests
    #     role-session-name: deploy_task_integration_tests
    #     aws-region: us-west-2

    # - name: Deploy Amazon ECS task definition with one-off task and wait for task stopped set to false
    #   uses: aws-actions/amazon-ecs-deploy-task-definition@d86f51829cb29dd510e3afc88018bfdcbec36cdd
    #   with:
    #     task-definition: task-definition-run-task.json
    #     cluster: github-actions-deploy-task-def-integ-test
    #     run-task: true
    #     run-task-subnets: subnet-e5604fce, subnet-fe9355b4, subnet-c49431bc, subnet-392f9b64
    #     run-task-assign-public-IP: ENABLED
    #     run-task-security-groups: sg-067ebcde49c0f3ad8
    #     run-task-launch-type: FARGATE
    #     wait-for-task-stopped: false

    # - name: Deploy Amazon ECS task definition with one-off task and wait for task stopped set to true
    #   uses: aws-actions/amazon-ecs-deploy-task-definition@d86f51829cb29dd510e3afc88018bfdcbec36cdd
    #   with:
    #     task-definition: task-definition-run-task.json
    #     cluster: github-actions-deploy-task-def-integ-test
    #     run-task: true
    #     run-task-subnets: subnet-e5604fce, subnet-fe9355b4, subnet-c49431bc, subnet-392f9b64
    #     run-task-assign-public-IP: ENABLED
    #     run-task-security-groups: sg-067ebcde49c0f3ad8
    #     run-task-launch-type: FARGATE
    #     wait-for-task-stopped: true
    #     enable-ecs-managed-tags: true

    # - name: Deploy Amazon ECS task definition with ECS Service
    #   uses: aws-actions/amazon-ecs-deploy-task-definition@d86f51829cb29dd510e3afc88018bfdcbec36cdd
    #   with:
    #     task-definition: task-definition.json
    #     service: github-actions-deploy-task-def-integ-test
    #     cluster: github-actions-deploy-task-def-integ-test
    #     wait-for-service-stability: true
    #     enable-ecs-managed-tags: true

  # !! Unfortunately, the `uses` function does not support contexts (i.e. variables)
  # https://stackoverflow.com/questions/75373413/reference-a-variable-in-uses-when-pointing-to-a-path-to-a-container
  # Thus, we are not able to dynamically call either a released action (e.g. `uses:aws-actions/amazon-ecs-deploy-task-definition@v1`) or a local action (e.g. `uses:./`) based on state.
  # As a workaround, we opt to use separate jobs.
  deploy_from_local_action:
    if: inputs.call_local_action == 'true'
    name: Deploy from local action
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::${{ secrets.account_id }}:role/GitHubActionsDeployTaskIntegrationTests
        role-session-name: deploy_task_integration_tests
        aws-region: us-west-2
    
    # All other integration tests would go here...

    - name: Deploy Amazon ECS task definition with ECS Service
      uses: ./
      with:
        task-definition: task-definition.json
        service: github-actions-deploy-task-def-integ-test
        cluster: github-actions-deploy-task-def-integ-test
        wait-for-service-stability: true
        enable-ecs-managed-tags: true
